/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type ContractStruct = {
  initiator: AddressLike;
  counterparties: AddressLike[];
  hashDigest: BigNumberish;
  url: string;
};

export type ContractStructOutput = [
  initiator: string,
  counterparties: string[],
  hashDigest: bigint,
  url: string
] & {
  initiator: string;
  counterparties: string[];
  hashDigest: bigint;
  url: string;
};

export type ContractDraftStruct = {
  content: ContractStruct;
  signatures: AddressLike[];
};

export type ContractDraftStructOutput = [
  content: ContractStructOutput,
  signatures: string[]
] & { content: ContractStructOutput; signatures: string[] };

export interface IContractNftInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "balanceOf"
      | "cancelContract"
      | "getApproved"
      | "getContract"
      | "getDraft"
      | "initContractAndSign"
      | "isApprovedForAll"
      | "isBlocked"
      | "isContractIdAvailable"
      | "ownerOf"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setBlocked"
      | "setupFeeAndAccount"
      | "signContract"
      | "supportsInterface"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "ContractCancelled"
      | "ContractCompleted"
      | "ContractInitiated"
      | "ContractSigned"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDraft",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initContractAndSign",
    values: [AddressLike[], BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isBlocked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isContractIdAvailable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setBlocked", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setupFeeAndAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDraft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initContractAndSign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isContractIdAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setupFeeAndAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractCancelledEvent {
  export type InputTuple = [contractId: BigNumberish];
  export type OutputTuple = [contractId: bigint];
  export interface OutputObject {
    contractId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractCompletedEvent {
  export type InputTuple = [contractId: BigNumberish, signer: AddressLike];
  export type OutputTuple = [contractId: bigint, signer: string];
  export interface OutputObject {
    contractId: bigint;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractInitiatedEvent {
  export type InputTuple = [contractId: BigNumberish, initiator: AddressLike];
  export type OutputTuple = [contractId: bigint, initiator: string];
  export interface OutputObject {
    contractId: bigint;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractSignedEvent {
  export type InputTuple = [contractId: BigNumberish, signer: AddressLike];
  export type OutputTuple = [contractId: bigint, signer: string];
  export interface OutputObject {
    contractId: bigint;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IContractNft extends BaseContract {
  connect(runner?: ContractRunner | null): IContractNft;
  waitForDeployment(): Promise<this>;

  interface: IContractNftInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  cancelContract: TypedContractMethod<
    [contractId: BigNumberish],
    [void],
    "payable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getContract: TypedContractMethod<
    [contractId: BigNumberish],
    [ContractStructOutput],
    "view"
  >;

  getDraft: TypedContractMethod<
    [contractId: BigNumberish],
    [ContractDraftStructOutput],
    "view"
  >;

  initContractAndSign: TypedContractMethod<
    [counterparties: AddressLike[], hashDigest: BigNumberish, url: string],
    [bigint],
    "payable"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  isBlocked: TypedContractMethod<[], [boolean], "view">;

  isContractIdAvailable: TypedContractMethod<
    [contractId: BigNumberish],
    [boolean],
    "view"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setBlocked: TypedContractMethod<[blocked: boolean], [void], "nonpayable">;

  setupFeeAndAccount: TypedContractMethod<
    [],
    [[bigint, string] & { fee: bigint; account: string }],
    "view"
  >;

  signContract: TypedContractMethod<
    [contractId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelContract"
  ): TypedContractMethod<[contractId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<
    [contractId: BigNumberish],
    [ContractStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDraft"
  ): TypedContractMethod<
    [contractId: BigNumberish],
    [ContractDraftStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initContractAndSign"
  ): TypedContractMethod<
    [counterparties: AddressLike[], hashDigest: BigNumberish, url: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBlocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isContractIdAvailable"
  ): TypedContractMethod<[contractId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBlocked"
  ): TypedContractMethod<[blocked: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setupFeeAndAccount"
  ): TypedContractMethod<
    [],
    [[bigint, string] & { fee: bigint; account: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "signContract"
  ): TypedContractMethod<[contractId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "ContractCancelled"
  ): TypedContractEvent<
    ContractCancelledEvent.InputTuple,
    ContractCancelledEvent.OutputTuple,
    ContractCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ContractCompleted"
  ): TypedContractEvent<
    ContractCompletedEvent.InputTuple,
    ContractCompletedEvent.OutputTuple,
    ContractCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ContractInitiated"
  ): TypedContractEvent<
    ContractInitiatedEvent.InputTuple,
    ContractInitiatedEvent.OutputTuple,
    ContractInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractSigned"
  ): TypedContractEvent<
    ContractSignedEvent.InputTuple,
    ContractSignedEvent.OutputTuple,
    ContractSignedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "ContractCancelled(uint256)": TypedContractEvent<
      ContractCancelledEvent.InputTuple,
      ContractCancelledEvent.OutputTuple,
      ContractCancelledEvent.OutputObject
    >;
    ContractCancelled: TypedContractEvent<
      ContractCancelledEvent.InputTuple,
      ContractCancelledEvent.OutputTuple,
      ContractCancelledEvent.OutputObject
    >;

    "ContractCompleted(uint256,address)": TypedContractEvent<
      ContractCompletedEvent.InputTuple,
      ContractCompletedEvent.OutputTuple,
      ContractCompletedEvent.OutputObject
    >;
    ContractCompleted: TypedContractEvent<
      ContractCompletedEvent.InputTuple,
      ContractCompletedEvent.OutputTuple,
      ContractCompletedEvent.OutputObject
    >;

    "ContractInitiated(uint256,address)": TypedContractEvent<
      ContractInitiatedEvent.InputTuple,
      ContractInitiatedEvent.OutputTuple,
      ContractInitiatedEvent.OutputObject
    >;
    ContractInitiated: TypedContractEvent<
      ContractInitiatedEvent.InputTuple,
      ContractInitiatedEvent.OutputTuple,
      ContractInitiatedEvent.OutputObject
    >;

    "ContractSigned(uint256,address)": TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;
    ContractSigned: TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
