/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IInfoDeskInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "InfoDesk_init"
      | "computeMachineRegistrationFee"
      | "computeTransactionFee"
      | "getAccount"
      | "getContract"
      | "getImplementation"
      | "getPrecompile"
      | "getValue"
      | "resetToDefaults"
      | "setAccount"
      | "setContract"
      | "setImplementation"
      | "setPrecompile"
      | "setValue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractUpdated"
      | "ImplementationUpdated"
      | "PrecompileUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "InfoDesk_init",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeMachineRegistrationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "computeTransactionFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrecompile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetToDefaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAccount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setContract",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementation",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrecompile",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setValue",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "InfoDesk_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeMachineRegistrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeTransactionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resetToDefaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrecompile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setValue", data: BytesLike): Result;
}

export namespace ContractUpdatedEvent {
  export type InputTuple = [
    contractType: BigNumberish,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    contractType: bigint,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    contractType: bigint;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationUpdatedEvent {
  export type InputTuple = [
    implementationType: BigNumberish,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    implementationType: bigint,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    implementationType: bigint;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrecompileUpdatedEvent {
  export type InputTuple = [
    precompileType: BigNumberish,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    precompileType: bigint,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    precompileType: bigint;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInfoDesk extends BaseContract {
  connect(runner?: ContractRunner | null): IInfoDesk;
  waitForDeployment(): Promise<this>;

  interface: IInfoDeskInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  InfoDesk_init: TypedContractMethod<
    [owner: AddressLike],
    [void],
    "nonpayable"
  >;

  computeMachineRegistrationFee: TypedContractMethod<
    [machineValue: BigNumberish],
    [bigint],
    "view"
  >;

  computeTransactionFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  getAccount: TypedContractMethod<
    [accountType: BigNumberish],
    [string],
    "view"
  >;

  getContract: TypedContractMethod<
    [contractType: BigNumberish],
    [string],
    "view"
  >;

  getImplementation: TypedContractMethod<
    [implementationType: BigNumberish],
    [string],
    "view"
  >;

  getPrecompile: TypedContractMethod<
    [precompileType: BigNumberish],
    [string],
    "view"
  >;

  getValue: TypedContractMethod<[valueType: BigNumberish], [bigint], "view">;

  resetToDefaults: TypedContractMethod<[], [void], "nonpayable">;

  setAccount: TypedContractMethod<
    [accountType: BigNumberish, newAccount: AddressLike],
    [void],
    "nonpayable"
  >;

  setContract: TypedContractMethod<
    [contractType: BigNumberish, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setImplementation: TypedContractMethod<
    [implementationType: BigNumberish, newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrecompile: TypedContractMethod<
    [precompileType: BigNumberish, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setValue: TypedContractMethod<
    [valueType: BigNumberish, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "InfoDesk_init"
  ): TypedContractMethod<[owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "computeMachineRegistrationFee"
  ): TypedContractMethod<[machineValue: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeTransactionFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAccount"
  ): TypedContractMethod<[accountType: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<[contractType: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[implementationType: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPrecompile"
  ): TypedContractMethod<[precompileType: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getValue"
  ): TypedContractMethod<[valueType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "resetToDefaults"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAccount"
  ): TypedContractMethod<
    [accountType: BigNumberish, newAccount: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setContract"
  ): TypedContractMethod<
    [contractType: BigNumberish, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setImplementation"
  ): TypedContractMethod<
    [implementationType: BigNumberish, newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPrecompile"
  ): TypedContractMethod<
    [precompileType: BigNumberish, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setValue"
  ): TypedContractMethod<
    [valueType: BigNumberish, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContractUpdated"
  ): TypedContractEvent<
    ContractUpdatedEvent.InputTuple,
    ContractUpdatedEvent.OutputTuple,
    ContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationUpdated"
  ): TypedContractEvent<
    ImplementationUpdatedEvent.InputTuple,
    ImplementationUpdatedEvent.OutputTuple,
    ImplementationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PrecompileUpdated"
  ): TypedContractEvent<
    PrecompileUpdatedEvent.InputTuple,
    PrecompileUpdatedEvent.OutputTuple,
    PrecompileUpdatedEvent.OutputObject
  >;

  filters: {
    "ContractUpdated(uint8,address,address)": TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;
    ContractUpdated: TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;

    "ImplementationUpdated(uint8,address,address)": TypedContractEvent<
      ImplementationUpdatedEvent.InputTuple,
      ImplementationUpdatedEvent.OutputTuple,
      ImplementationUpdatedEvent.OutputObject
    >;
    ImplementationUpdated: TypedContractEvent<
      ImplementationUpdatedEvent.InputTuple,
      ImplementationUpdatedEvent.OutputTuple,
      ImplementationUpdatedEvent.OutputObject
    >;

    "PrecompileUpdated(uint8,address,address)": TypedContractEvent<
      PrecompileUpdatedEvent.InputTuple,
      PrecompileUpdatedEvent.OutputTuple,
      PrecompileUpdatedEvent.OutputObject
    >;
    PrecompileUpdated: TypedContractEvent<
      PrecompileUpdatedEvent.InputTuple,
      PrecompileUpdatedEvent.OutputTuple,
      PrecompileUpdatedEvent.OutputObject
    >;
  };
}
