/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IPeaqRwaNftInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addContractNft"
      | "addMachineIssuer"
      | "addMachineRegulator"
      | "findContractNft"
      | "getMachineIssuers"
      | "getMachineNftByIssuer"
      | "getMachineRegulators"
      | "isContractNft"
      | "isMachineNft"
      | "isRwaNft"
      | "removeMachineIssuer"
      | "removeMachineRegulator"
      | "setMachineNftBlockState"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractNftAdded"
      | "MachineIssuerAdded"
      | "MachineIssuerRemoved"
      | "MachineRegulatorAdded"
      | "MachineRegulatorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addContractNft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMachineIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addMachineRegulator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findContractNft",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMachineIssuers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMachineNftByIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMachineRegulators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isContractNft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMachineNft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRwaNft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMachineIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMachineRegulator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMachineNftBlockState",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "addContractNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMachineIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMachineRegulator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findContractNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMachineIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMachineNftByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMachineRegulators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMachineNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRwaNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMachineIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMachineRegulator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMachineNftBlockState",
    data: BytesLike
  ): Result;
}

export namespace ContractNftAddedEvent {
  export type InputTuple = [contractNft: AddressLike];
  export type OutputTuple = [contractNft: string];
  export interface OutputObject {
    contractNft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MachineIssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike, machineNft: AddressLike];
  export type OutputTuple = [issuer: string, machineNft: string];
  export interface OutputObject {
    issuer: string;
    machineNft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MachineIssuerRemovedEvent {
  export type InputTuple = [regulator: AddressLike, issuer: AddressLike];
  export type OutputTuple = [regulator: string, issuer: string];
  export interface OutputObject {
    regulator: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MachineRegulatorAddedEvent {
  export type InputTuple = [regulator: AddressLike];
  export type OutputTuple = [regulator: string];
  export interface OutputObject {
    regulator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MachineRegulatorRemovedEvent {
  export type InputTuple = [regulator: AddressLike];
  export type OutputTuple = [regulator: string];
  export interface OutputObject {
    regulator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPeaqRwaNft extends BaseContract {
  connect(runner?: ContractRunner | null): IPeaqRwaNft;
  waitForDeployment(): Promise<this>;

  interface: IPeaqRwaNftInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addContractNft: TypedContractMethod<[], [void], "nonpayable">;

  addMachineIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  addMachineRegulator: TypedContractMethod<
    [regulator: AddressLike],
    [void],
    "nonpayable"
  >;

  findContractNft: TypedContractMethod<
    [contractId: BigNumberish],
    [string],
    "view"
  >;

  getMachineIssuers: TypedContractMethod<[], [string[]], "view">;

  getMachineNftByIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [string],
    "view"
  >;

  getMachineRegulators: TypedContractMethod<[], [string[]], "view">;

  isContractNft: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isMachineNft: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isRwaNft: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  removeMachineIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  removeMachineRegulator: TypedContractMethod<
    [regulator: AddressLike],
    [void],
    "nonpayable"
  >;

  setMachineNftBlockState: TypedContractMethod<
    [issuerOrContractNft: AddressLike, blocked: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addContractNft"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addMachineIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addMachineRegulator"
  ): TypedContractMethod<[regulator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "findContractNft"
  ): TypedContractMethod<[contractId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMachineIssuers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMachineNftByIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMachineRegulators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isContractNft"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMachineNft"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRwaNft"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeMachineIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeMachineRegulator"
  ): TypedContractMethod<[regulator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMachineNftBlockState"
  ): TypedContractMethod<
    [issuerOrContractNft: AddressLike, blocked: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContractNftAdded"
  ): TypedContractEvent<
    ContractNftAddedEvent.InputTuple,
    ContractNftAddedEvent.OutputTuple,
    ContractNftAddedEvent.OutputObject
  >;
  getEvent(
    key: "MachineIssuerAdded"
  ): TypedContractEvent<
    MachineIssuerAddedEvent.InputTuple,
    MachineIssuerAddedEvent.OutputTuple,
    MachineIssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "MachineIssuerRemoved"
  ): TypedContractEvent<
    MachineIssuerRemovedEvent.InputTuple,
    MachineIssuerRemovedEvent.OutputTuple,
    MachineIssuerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MachineRegulatorAdded"
  ): TypedContractEvent<
    MachineRegulatorAddedEvent.InputTuple,
    MachineRegulatorAddedEvent.OutputTuple,
    MachineRegulatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "MachineRegulatorRemoved"
  ): TypedContractEvent<
    MachineRegulatorRemovedEvent.InputTuple,
    MachineRegulatorRemovedEvent.OutputTuple,
    MachineRegulatorRemovedEvent.OutputObject
  >;

  filters: {
    "ContractNftAdded(address)": TypedContractEvent<
      ContractNftAddedEvent.InputTuple,
      ContractNftAddedEvent.OutputTuple,
      ContractNftAddedEvent.OutputObject
    >;
    ContractNftAdded: TypedContractEvent<
      ContractNftAddedEvent.InputTuple,
      ContractNftAddedEvent.OutputTuple,
      ContractNftAddedEvent.OutputObject
    >;

    "MachineIssuerAdded(address,address)": TypedContractEvent<
      MachineIssuerAddedEvent.InputTuple,
      MachineIssuerAddedEvent.OutputTuple,
      MachineIssuerAddedEvent.OutputObject
    >;
    MachineIssuerAdded: TypedContractEvent<
      MachineIssuerAddedEvent.InputTuple,
      MachineIssuerAddedEvent.OutputTuple,
      MachineIssuerAddedEvent.OutputObject
    >;

    "MachineIssuerRemoved(address,address)": TypedContractEvent<
      MachineIssuerRemovedEvent.InputTuple,
      MachineIssuerRemovedEvent.OutputTuple,
      MachineIssuerRemovedEvent.OutputObject
    >;
    MachineIssuerRemoved: TypedContractEvent<
      MachineIssuerRemovedEvent.InputTuple,
      MachineIssuerRemovedEvent.OutputTuple,
      MachineIssuerRemovedEvent.OutputObject
    >;

    "MachineRegulatorAdded(address)": TypedContractEvent<
      MachineRegulatorAddedEvent.InputTuple,
      MachineRegulatorAddedEvent.OutputTuple,
      MachineRegulatorAddedEvent.OutputObject
    >;
    MachineRegulatorAdded: TypedContractEvent<
      MachineRegulatorAddedEvent.InputTuple,
      MachineRegulatorAddedEvent.OutputTuple,
      MachineRegulatorAddedEvent.OutputObject
    >;

    "MachineRegulatorRemoved(address)": TypedContractEvent<
      MachineRegulatorRemovedEvent.InputTuple,
      MachineRegulatorRemovedEvent.OutputTuple,
      MachineRegulatorRemovedEvent.OutputObject
    >;
    MachineRegulatorRemoved: TypedContractEvent<
      MachineRegulatorRemovedEvent.InputTuple,
      MachineRegulatorRemovedEvent.OutputTuple,
      MachineRegulatorRemovedEvent.OutputObject
    >;
  };
}
