/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IPeaqVaultFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createVault"
      | "isPeaqVault"
      | "pauseVaultToken"
      | "unpauseVaultToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "VaultCreated"
      | "VaultTokenPaused"
      | "VaultTokenUnpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createVault",
    values: [
      AddressLike,
      string,
      string,
      AddressLike,
      AddressLike,
      AddressLike[],
      BigNumberish[],
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isPeaqVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseVaultToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseVaultToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPeaqVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseVaultToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseVaultToken",
    data: BytesLike
  ): Result;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    token: AddressLike,
    distributor: AddressLike
  ];
  export type OutputTuple = [vault: string, token: string, distributor: string];
  export interface OutputObject {
    vault: string;
    token: string;
    distributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultTokenPausedEvent {
  export type InputTuple = [vault: AddressLike, token: AddressLike];
  export type OutputTuple = [vault: string, token: string];
  export interface OutputObject {
    vault: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultTokenUnpausedEvent {
  export type InputTuple = [vault: AddressLike, token: AddressLike];
  export type OutputTuple = [vault: string, token: string];
  export interface OutputObject {
    vault: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPeaqVaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IPeaqVaultFactory;
  waitForDeployment(): Promise<this>;

  interface: IPeaqVaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVault: TypedContractMethod<
    [
      vaultTaker: AddressLike,
      name: string,
      symbol: string,
      asset: AddressLike,
      tokenIdentity: AddressLike,
      claimIssuers: AddressLike[],
      claimTopics: BigNumberish[],
      complianceModules: AddressLike[]
    ],
    [
      [string, string, string] & {
        vaultAddr: string;
        tokenAddr: string;
        distributorAddr: string;
      }
    ],
    "nonpayable"
  >;

  isPeaqVault: TypedContractMethod<[vault: AddressLike], [boolean], "view">;

  pauseVaultToken: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseVaultToken: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      vaultTaker: AddressLike,
      name: string,
      symbol: string,
      asset: AddressLike,
      tokenIdentity: AddressLike,
      claimIssuers: AddressLike[],
      claimTopics: BigNumberish[],
      complianceModules: AddressLike[]
    ],
    [
      [string, string, string] & {
        vaultAddr: string;
        tokenAddr: string;
        distributorAddr: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isPeaqVault"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pauseVaultToken"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseVaultToken"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultTokenPaused"
  ): TypedContractEvent<
    VaultTokenPausedEvent.InputTuple,
    VaultTokenPausedEvent.OutputTuple,
    VaultTokenPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultTokenUnpaused"
  ): TypedContractEvent<
    VaultTokenUnpausedEvent.InputTuple,
    VaultTokenUnpausedEvent.OutputTuple,
    VaultTokenUnpausedEvent.OutputObject
  >;

  filters: {
    "VaultCreated(address,address,address)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultTokenPaused(address,address)": TypedContractEvent<
      VaultTokenPausedEvent.InputTuple,
      VaultTokenPausedEvent.OutputTuple,
      VaultTokenPausedEvent.OutputObject
    >;
    VaultTokenPaused: TypedContractEvent<
      VaultTokenPausedEvent.InputTuple,
      VaultTokenPausedEvent.OutputTuple,
      VaultTokenPausedEvent.OutputObject
    >;

    "VaultTokenUnpaused(address,address)": TypedContractEvent<
      VaultTokenUnpausedEvent.InputTuple,
      VaultTokenUnpausedEvent.OutputTuple,
      VaultTokenUnpausedEvent.OutputObject
    >;
    VaultTokenUnpaused: TypedContractEvent<
      VaultTokenUnpausedEvent.InputTuple,
      VaultTokenUnpausedEvent.OutputTuple,
      VaultTokenUnpausedEvent.OutputObject
    >;
  };
}
