/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPeaqVault {
  export type NFTStruct = { machineNft: AddressLike; tokenId: BigNumberish };

  export type NFTStructOutput = [machineNft: string, tokenId: bigint] & {
    machineNft: string;
    tokenId: bigint;
  };
}

export interface IPeaqVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "configureKycRequirement"
      | "depositAndMint"
      | "depositor"
      | "identityRegistry"
      | "minted"
      | "nfts"
      | "redeemed"
      | "rewardDistributor"
      | "setRewardDistributor"
      | "setToken"
      | "setVaultTaker"
      | "supportsInterface"
      | "token"
      | "transactionFeeAndAccount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Burned"
      | "Deposited"
      | "Minted"
      | "TokenSet"
      | "VaultTakerSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "configureKycRequirement",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndMint",
    values: [AddressLike[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "depositor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "minted", values?: undefined): string;
  encodeFunctionData(functionFragment: "nfts", values?: undefined): string;
  encodeFunctionData(functionFragment: "redeemed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rewardDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultTaker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transactionFeeAndAccount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "configureKycRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nfts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVaultTaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionFeeAndAccount",
    data: BytesLike
  ): Result;
}

export namespace BurnedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    from: AddressLike,
    machineNft: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, machineNft: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    machineNft: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSetEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultTakerSetEvent {
  export type InputTuple = [vaultTaker: AddressLike];
  export type OutputTuple = [vaultTaker: string];
  export interface OutputObject {
    vaultTaker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPeaqVault extends BaseContract {
  connect(runner?: ContractRunner | null): IPeaqVault;
  waitForDeployment(): Promise<this>;

  interface: IPeaqVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configureKycRequirement: TypedContractMethod<
    [claimIssuers: AddressLike[], claimTopics: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  depositAndMint: TypedContractMethod<
    [rwaNft: AddressLike[], tokenIds: BigNumberish[], amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositor: TypedContractMethod<[], [string], "view">;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  minted: TypedContractMethod<[], [boolean], "view">;

  nfts: TypedContractMethod<[], [IPeaqVault.NFTStructOutput[]], "view">;

  redeemed: TypedContractMethod<[], [boolean], "view">;

  rewardDistributor: TypedContractMethod<[], [string], "view">;

  setRewardDistributor: TypedContractMethod<
    [distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  setToken: TypedContractMethod<[token_: AddressLike], [void], "nonpayable">;

  setVaultTaker: TypedContractMethod<
    [vaultTaker: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transactionFeeAndAccount: TypedContractMethod<
    [amount: BigNumberish],
    [[bigint, string] & { fee: bigint; account: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configureKycRequirement"
  ): TypedContractMethod<
    [claimIssuers: AddressLike[], claimTopics: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositAndMint"
  ): TypedContractMethod<
    [rwaNft: AddressLike[], tokenIds: BigNumberish[], amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "nfts"
  ): TypedContractMethod<[], [IPeaqVault.NFTStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "redeemed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rewardDistributor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setRewardDistributor"
  ): TypedContractMethod<[distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setToken"
  ): TypedContractMethod<[token_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultTaker"
  ): TypedContractMethod<[vaultTaker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transactionFeeAndAccount"
  ): TypedContractMethod<
    [amount: BigNumberish],
    [[bigint, string] & { fee: bigint; account: string }],
    "view"
  >;

  getEvent(
    key: "Burned"
  ): TypedContractEvent<
    BurnedEvent.InputTuple,
    BurnedEvent.OutputTuple,
    BurnedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Minted"
  ): TypedContractEvent<
    MintedEvent.InputTuple,
    MintedEvent.OutputTuple,
    MintedEvent.OutputObject
  >;
  getEvent(
    key: "TokenSet"
  ): TypedContractEvent<
    TokenSetEvent.InputTuple,
    TokenSetEvent.OutputTuple,
    TokenSetEvent.OutputObject
  >;
  getEvent(
    key: "VaultTakerSet"
  ): TypedContractEvent<
    VaultTakerSetEvent.InputTuple,
    VaultTakerSetEvent.OutputTuple,
    VaultTakerSetEvent.OutputObject
  >;

  filters: {
    "Burned(address,uint256)": TypedContractEvent<
      BurnedEvent.InputTuple,
      BurnedEvent.OutputTuple,
      BurnedEvent.OutputObject
    >;
    Burned: TypedContractEvent<
      BurnedEvent.InputTuple,
      BurnedEvent.OutputTuple,
      BurnedEvent.OutputObject
    >;

    "Deposited(address,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Minted(address,uint256)": TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;
    Minted: TypedContractEvent<
      MintedEvent.InputTuple,
      MintedEvent.OutputTuple,
      MintedEvent.OutputObject
    >;

    "TokenSet(address)": TypedContractEvent<
      TokenSetEvent.InputTuple,
      TokenSetEvent.OutputTuple,
      TokenSetEvent.OutputObject
    >;
    TokenSet: TypedContractEvent<
      TokenSetEvent.InputTuple,
      TokenSetEvent.OutputTuple,
      TokenSetEvent.OutputObject
    >;

    "VaultTakerSet(address)": TypedContractEvent<
      VaultTakerSetEvent.InputTuple,
      VaultTakerSetEvent.OutputTuple,
      VaultTakerSetEvent.OutputObject
    >;
    VaultTakerSet: TypedContractEvent<
      VaultTakerSetEvent.InputTuple,
      VaultTakerSetEvent.OutputTuple,
      VaultTakerSetEvent.OutputObject
    >;
  };
}
