/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.0
 * source: utils/did/did_document_format.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from 'google-protobuf';
export namespace document {
  export enum SubjectType {
    MACHINE = 0
  }
  export enum VerificationType {
    Ed25519VerificationKey2020 = 0,
    Sr25519VerificationKey2020 = 1,
    EcdsaSecp256k1RecoveryMethod2020 = 2
  }
  export class MachineSubject extends pb_1.Message {
    #one_of_decls: number[][] = [
      [1],
      [2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9],
      [10]
    ];
    constructor(
      data?:
        | any[]
        | ({} & (
            | {
                type?: string;
              }
            | {
                manufacturer?: string;
              }
            | {
                model?: string;
              }
            | {
                version?: string;
              }
            | {
                edition?: string;
              }
            | {
                color?: string;
              }
            | {
                day_of_manufacture?: string;
              }
            | {
                country?: string;
              }
            | {
                city?: string;
              }
            | {
                serial_number?: string;
              }
          ))
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('type' in data && data.type != undefined) {
          this.type = data.type;
        }
        if ('manufacturer' in data && data.manufacturer != undefined) {
          this.manufacturer = data.manufacturer;
        }
        if ('model' in data && data.model != undefined) {
          this.model = data.model;
        }
        if ('version' in data && data.version != undefined) {
          this.version = data.version;
        }
        if ('edition' in data && data.edition != undefined) {
          this.edition = data.edition;
        }
        if ('color' in data && data.color != undefined) {
          this.color = data.color;
        }
        if (
          'day_of_manufacture' in data &&
          data.day_of_manufacture != undefined
        ) {
          this.day_of_manufacture = data.day_of_manufacture;
        }
        if ('country' in data && data.country != undefined) {
          this.country = data.country;
        }
        if ('city' in data && data.city != undefined) {
          this.city = data.city;
        }
        if ('serial_number' in data && data.serial_number != undefined) {
          this.serial_number = data.serial_number;
        }
      }
    }
    get type() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set type(value: string) {
      pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_type() {
      return pb_1.Message.getField(this, 1) != null;
    }
    get manufacturer() {
      return pb_1.Message.getFieldWithDefault(this, 2, '') as string;
    }
    set manufacturer(value: string) {
      pb_1.Message.setOneofField(this, 2, this.#one_of_decls[1], value);
    }
    get has_manufacturer() {
      return pb_1.Message.getField(this, 2) != null;
    }
    get model() {
      return pb_1.Message.getFieldWithDefault(this, 3, '') as string;
    }
    set model(value: string) {
      pb_1.Message.setOneofField(this, 3, this.#one_of_decls[2], value);
    }
    get has_model() {
      return pb_1.Message.getField(this, 3) != null;
    }
    get version() {
      return pb_1.Message.getFieldWithDefault(this, 4, '') as string;
    }
    set version(value: string) {
      pb_1.Message.setOneofField(this, 4, this.#one_of_decls[3], value);
    }
    get has_version() {
      return pb_1.Message.getField(this, 4) != null;
    }
    get edition() {
      return pb_1.Message.getFieldWithDefault(this, 5, '') as string;
    }
    set edition(value: string) {
      pb_1.Message.setOneofField(this, 5, this.#one_of_decls[4], value);
    }
    get has_edition() {
      return pb_1.Message.getField(this, 5) != null;
    }
    get color() {
      return pb_1.Message.getFieldWithDefault(this, 6, '') as string;
    }
    set color(value: string) {
      pb_1.Message.setOneofField(this, 6, this.#one_of_decls[5], value);
    }
    get has_color() {
      return pb_1.Message.getField(this, 6) != null;
    }
    get day_of_manufacture() {
      return pb_1.Message.getFieldWithDefault(this, 7, '') as string;
    }
    set day_of_manufacture(value: string) {
      pb_1.Message.setOneofField(this, 7, this.#one_of_decls[6], value);
    }
    get has_day_of_manufacture() {
      return pb_1.Message.getField(this, 7) != null;
    }
    get country() {
      return pb_1.Message.getFieldWithDefault(this, 8, '') as string;
    }
    set country(value: string) {
      pb_1.Message.setOneofField(this, 8, this.#one_of_decls[7], value);
    }
    get has_country() {
      return pb_1.Message.getField(this, 8) != null;
    }
    get city() {
      return pb_1.Message.getFieldWithDefault(this, 9, '') as string;
    }
    set city(value: string) {
      pb_1.Message.setOneofField(this, 9, this.#one_of_decls[8], value);
    }
    get has_city() {
      return pb_1.Message.getField(this, 9) != null;
    }
    get serial_number() {
      return pb_1.Message.getFieldWithDefault(this, 10, '') as string;
    }
    set serial_number(value: string) {
      pb_1.Message.setOneofField(this, 10, this.#one_of_decls[9], value);
    }
    get has_serial_number() {
      return pb_1.Message.getField(this, 10) != null;
    }
    get _type() {
      const cases: {
        [index: number]: 'none' | 'type';
      } = {
        0: 'none',
        1: 'type'
      };
      return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    get _manufacturer() {
      const cases: {
        [index: number]: 'none' | 'manufacturer';
      } = {
        0: 'none',
        2: 'manufacturer'
      };
      return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    get _model() {
      const cases: {
        [index: number]: 'none' | 'model';
      } = {
        0: 'none',
        3: 'model'
      };
      return cases[pb_1.Message.computeOneofCase(this, [3])];
    }
    get _version() {
      const cases: {
        [index: number]: 'none' | 'version';
      } = {
        0: 'none',
        4: 'version'
      };
      return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    get _edition() {
      const cases: {
        [index: number]: 'none' | 'edition';
      } = {
        0: 'none',
        5: 'edition'
      };
      return cases[pb_1.Message.computeOneofCase(this, [5])];
    }
    get _color() {
      const cases: {
        [index: number]: 'none' | 'color';
      } = {
        0: 'none',
        6: 'color'
      };
      return cases[pb_1.Message.computeOneofCase(this, [6])];
    }
    get _day_of_manufacture() {
      const cases: {
        [index: number]: 'none' | 'day_of_manufacture';
      } = {
        0: 'none',
        7: 'day_of_manufacture'
      };
      return cases[pb_1.Message.computeOneofCase(this, [7])];
    }
    get _country() {
      const cases: {
        [index: number]: 'none' | 'country';
      } = {
        0: 'none',
        8: 'country'
      };
      return cases[pb_1.Message.computeOneofCase(this, [8])];
    }
    get _city() {
      const cases: {
        [index: number]: 'none' | 'city';
      } = {
        0: 'none',
        9: 'city'
      };
      return cases[pb_1.Message.computeOneofCase(this, [9])];
    }
    get _serial_number() {
      const cases: {
        [index: number]: 'none' | 'serial_number';
      } = {
        0: 'none',
        10: 'serial_number'
      };
      return cases[pb_1.Message.computeOneofCase(this, [10])];
    }
    static fromObject(data: {
      type?: string;
      manufacturer?: string;
      model?: string;
      version?: string;
      edition?: string;
      color?: string;
      day_of_manufacture?: string;
      country?: string;
      city?: string;
      serial_number?: string;
    }): MachineSubject {
      const message = new MachineSubject({});
      if (data.type != null) {
        message.type = data.type;
      }
      if (data.manufacturer != null) {
        message.manufacturer = data.manufacturer;
      }
      if (data.model != null) {
        message.model = data.model;
      }
      if (data.version != null) {
        message.version = data.version;
      }
      if (data.edition != null) {
        message.edition = data.edition;
      }
      if (data.color != null) {
        message.color = data.color;
      }
      if (data.day_of_manufacture != null) {
        message.day_of_manufacture = data.day_of_manufacture;
      }
      if (data.country != null) {
        message.country = data.country;
      }
      if (data.city != null) {
        message.city = data.city;
      }
      if (data.serial_number != null) {
        message.serial_number = data.serial_number;
      }
      return message;
    }
    toObject() {
      const data: {
        type?: string;
        manufacturer?: string;
        model?: string;
        version?: string;
        edition?: string;
        color?: string;
        day_of_manufacture?: string;
        country?: string;
        city?: string;
        serial_number?: string;
      } = {};
      if (this.type != null) {
        data.type = this.type;
      }
      if (this.manufacturer != null) {
        data.manufacturer = this.manufacturer;
      }
      if (this.model != null) {
        data.model = this.model;
      }
      if (this.version != null) {
        data.version = this.version;
      }
      if (this.edition != null) {
        data.edition = this.edition;
      }
      if (this.color != null) {
        data.color = this.color;
      }
      if (this.day_of_manufacture != null) {
        data.day_of_manufacture = this.day_of_manufacture;
      }
      if (this.country != null) {
        data.country = this.country;
      }
      if (this.city != null) {
        data.city = this.city;
      }
      if (this.serial_number != null) {
        data.serial_number = this.serial_number;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.has_type) writer.writeString(1, this.type);
      if (this.has_manufacturer) writer.writeString(2, this.manufacturer);
      if (this.has_model) writer.writeString(3, this.model);
      if (this.has_version) writer.writeString(4, this.version);
      if (this.has_edition) writer.writeString(5, this.edition);
      if (this.has_color) writer.writeString(6, this.color);
      if (this.has_day_of_manufacture)
        writer.writeString(7, this.day_of_manufacture);
      if (this.has_country) writer.writeString(8, this.country);
      if (this.has_city) writer.writeString(9, this.city);
      if (this.has_serial_number) writer.writeString(10, this.serial_number);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MachineSubject {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new MachineSubject();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.type = reader.readString();
            break;
          case 2:
            message.manufacturer = reader.readString();
            break;
          case 3:
            message.model = reader.readString();
            break;
          case 4:
            message.version = reader.readString();
            break;
          case 5:
            message.edition = reader.readString();
            break;
          case 6:
            message.color = reader.readString();
            break;
          case 7:
            message.day_of_manufacture = reader.readString();
            break;
          case 8:
            message.country = reader.readString();
            break;
          case 9:
            message.city = reader.readString();
            break;
          case 10:
            message.serial_number = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): MachineSubject {
      return MachineSubject.deserialize(bytes);
    }
  }
  export class CredentialSubject extends pb_1.Message {
    #one_of_decls: number[][] = [[3], [1]];
    constructor(
      data?:
        | any[]
        | ({
            type?: SubjectType;
          } & (
            | {
                machine?: MachineSubject;
              }
            | {
                id?: string;
              }
          ))
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('id' in data && data.id != undefined) {
          this.id = data.id;
        }
        if ('type' in data && data.type != undefined) {
          this.type = data.type;
        }
        if ('machine' in data && data.machine != undefined) {
          this.machine = data.machine;
        }
      }
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set id(value: string) {
      pb_1.Message.setOneofField(this, 1, this.#one_of_decls[1], value);
    }
    get has_id() {
      return pb_1.Message.getField(this, 1) != null;
    }
    get type() {
      return pb_1.Message.getFieldWithDefault(
        this,
        2,
        SubjectType.MACHINE
      ) as SubjectType;
    }
    set type(value: SubjectType) {
      pb_1.Message.setField(this, 2, value);
    }
    get machine() {
      return pb_1.Message.getWrapperField(
        this,
        MachineSubject,
        3
      ) as MachineSubject;
    }
    set machine(value: MachineSubject) {
      pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[0], value);
    }
    get has_machine() {
      return pb_1.Message.getField(this, 3) != null;
    }
    get subject() {
      const cases: {
        [index: number]: 'none' | 'machine';
      } = {
        0: 'none',
        3: 'machine'
      };
      return cases[pb_1.Message.computeOneofCase(this, [3])];
    }
    get _id() {
      const cases: {
        [index: number]: 'none' | 'id';
      } = {
        0: 'none',
        1: 'id'
      };
      return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    static fromObject(data: {
      id?: string;
      type?: SubjectType;
      machine?: ReturnType<typeof MachineSubject.prototype.toObject>;
    }): CredentialSubject {
      const message = new CredentialSubject({});
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.type != null) {
        message.type = data.type;
      }
      if (data.machine != null) {
        message.machine = MachineSubject.fromObject(data.machine);
      }
      return message;
    }
    toObject() {
      const data: {
        id?: string;
        type?: SubjectType;
        machine?: ReturnType<typeof MachineSubject.prototype.toObject>;
      } = {};
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.type != null) {
        data.type = this.type;
      }
      if (this.machine != null) {
        data.machine = this.machine.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.has_id) writer.writeString(1, this.id);
      if (this.type != SubjectType.MACHINE) writer.writeEnum(2, this.type);
      if (this.has_machine)
        writer.writeMessage(3, this.machine, () =>
          this.machine.serialize(writer)
        );
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader
    ): CredentialSubject {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new CredentialSubject();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.id = reader.readString();
            break;
          case 2:
            message.type = reader.readEnum();
            break;
          case 3:
            reader.readMessage(
              message.machine,
              () => (message.machine = MachineSubject.deserialize(reader))
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CredentialSubject {
      return CredentialSubject.deserialize(bytes);
    }
  }
  export class VerifiableCredential extends pb_1.Message {
    #one_of_decls: number[][] = [[1], [2], [3], [4], [5], [6]];
    constructor(
      data?:
        | any[]
        | ({} & (
            | {
                context?: string;
              }
            | {
                id?: string;
              }
            | {
                type?: string;
              }
            | {
                issuer?: string;
              }
            | {
                issuance_date?: string;
              }
            | {
                credential_subject?: CredentialSubject;
              }
          ))
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('context' in data && data.context != undefined) {
          this.context = data.context;
        }
        if ('id' in data && data.id != undefined) {
          this.id = data.id;
        }
        if ('type' in data && data.type != undefined) {
          this.type = data.type;
        }
        if ('issuer' in data && data.issuer != undefined) {
          this.issuer = data.issuer;
        }
        if ('issuance_date' in data && data.issuance_date != undefined) {
          this.issuance_date = data.issuance_date;
        }
        if (
          'credential_subject' in data &&
          data.credential_subject != undefined
        ) {
          this.credential_subject = data.credential_subject;
        }
      }
    }
    get context() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set context(value: string) {
      pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_context() {
      return pb_1.Message.getField(this, 1) != null;
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 2, '') as string;
    }
    set id(value: string) {
      pb_1.Message.setOneofField(this, 2, this.#one_of_decls[1], value);
    }
    get has_id() {
      return pb_1.Message.getField(this, 2) != null;
    }
    get type() {
      return pb_1.Message.getFieldWithDefault(this, 3, '') as string;
    }
    set type(value: string) {
      pb_1.Message.setOneofField(this, 3, this.#one_of_decls[2], value);
    }
    get has_type() {
      return pb_1.Message.getField(this, 3) != null;
    }
    get issuer() {
      return pb_1.Message.getFieldWithDefault(this, 4, '') as string;
    }
    set issuer(value: string) {
      pb_1.Message.setOneofField(this, 4, this.#one_of_decls[3], value);
    }
    get has_issuer() {
      return pb_1.Message.getField(this, 4) != null;
    }
    get issuance_date() {
      return pb_1.Message.getFieldWithDefault(this, 5, '') as string;
    }
    set issuance_date(value: string) {
      pb_1.Message.setOneofField(this, 5, this.#one_of_decls[4], value);
    }
    get has_issuance_date() {
      return pb_1.Message.getField(this, 5) != null;
    }
    get credential_subject() {
      return pb_1.Message.getWrapperField(
        this,
        CredentialSubject,
        6
      ) as CredentialSubject;
    }
    set credential_subject(value: CredentialSubject) {
      pb_1.Message.setOneofWrapperField(this, 6, this.#one_of_decls[5], value);
    }
    get has_credential_subject() {
      return pb_1.Message.getField(this, 6) != null;
    }
    get _context() {
      const cases: {
        [index: number]: 'none' | 'context';
      } = {
        0: 'none',
        1: 'context'
      };
      return cases[pb_1.Message.computeOneofCase(this, [1])];
    }
    get _id() {
      const cases: {
        [index: number]: 'none' | 'id';
      } = {
        0: 'none',
        2: 'id'
      };
      return cases[pb_1.Message.computeOneofCase(this, [2])];
    }
    get _type() {
      const cases: {
        [index: number]: 'none' | 'type';
      } = {
        0: 'none',
        3: 'type'
      };
      return cases[pb_1.Message.computeOneofCase(this, [3])];
    }
    get _issuer() {
      const cases: {
        [index: number]: 'none' | 'issuer';
      } = {
        0: 'none',
        4: 'issuer'
      };
      return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    get _issuance_date() {
      const cases: {
        [index: number]: 'none' | 'issuance_date';
      } = {
        0: 'none',
        5: 'issuance_date'
      };
      return cases[pb_1.Message.computeOneofCase(this, [5])];
    }
    get _credential_subject() {
      const cases: {
        [index: number]: 'none' | 'credential_subject';
      } = {
        0: 'none',
        6: 'credential_subject'
      };
      return cases[pb_1.Message.computeOneofCase(this, [6])];
    }
    static fromObject(data: {
      context?: string;
      id?: string;
      type?: string;
      issuer?: string;
      issuance_date?: string;
      credential_subject?: ReturnType<
        typeof CredentialSubject.prototype.toObject
      >;
    }): VerifiableCredential {
      const message = new VerifiableCredential({});
      if (data.context != null) {
        message.context = data.context;
      }
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.type != null) {
        message.type = data.type;
      }
      if (data.issuer != null) {
        message.issuer = data.issuer;
      }
      if (data.issuance_date != null) {
        message.issuance_date = data.issuance_date;
      }
      if (data.credential_subject != null) {
        message.credential_subject = CredentialSubject.fromObject(
          data.credential_subject
        );
      }
      return message;
    }
    toObject() {
      const data: {
        context?: string;
        id?: string;
        type?: string;
        issuer?: string;
        issuance_date?: string;
        credential_subject?: ReturnType<
          typeof CredentialSubject.prototype.toObject
        >;
      } = {};
      if (this.context != null) {
        data.context = this.context;
      }
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.type != null) {
        data.type = this.type;
      }
      if (this.issuer != null) {
        data.issuer = this.issuer;
      }
      if (this.issuance_date != null) {
        data.issuance_date = this.issuance_date;
      }
      if (this.credential_subject != null) {
        data.credential_subject = this.credential_subject.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.has_context) writer.writeString(1, this.context);
      if (this.has_id) writer.writeString(2, this.id);
      if (this.has_type) writer.writeString(3, this.type);
      if (this.has_issuer) writer.writeString(4, this.issuer);
      if (this.has_issuance_date) writer.writeString(5, this.issuance_date);
      if (this.has_credential_subject)
        writer.writeMessage(6, this.credential_subject, () =>
          this.credential_subject.serialize(writer)
        );
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader
    ): VerifiableCredential {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new VerifiableCredential();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.context = reader.readString();
            break;
          case 2:
            message.id = reader.readString();
            break;
          case 3:
            message.type = reader.readString();
            break;
          case 4:
            message.issuer = reader.readString();
            break;
          case 5:
            message.issuance_date = reader.readString();
            break;
          case 6:
            reader.readMessage(
              message.credential_subject,
              () =>
                (message.credential_subject =
                  CredentialSubject.deserialize(reader))
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): VerifiableCredential {
      return VerifiableCredential.deserialize(bytes);
    }
  }
  export class VerificationMethod extends pb_1.Message {
    #one_of_decls: number[][] = [[4], [5]];
    constructor(
      data?:
        | any[]
        | ({
            id?: string;
            type?: string;
            controller?: string;
          } & (
            | {
                public_key_multibase?: string;
              }
            | {
                blockchain_account_id?: string;
              }
          ))
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('id' in data && data.id != undefined) {
          this.id = data.id;
        }
        if ('type' in data && data.type != undefined) {
          this.type = data.type;
        }
        if ('controller' in data && data.controller != undefined) {
          this.controller = data.controller;
        }
        if (
          'public_key_multibase' in data &&
          data.public_key_multibase != undefined
        ) {
          this.public_key_multibase = data.public_key_multibase;
        }
        if (
          'blockchain_account_id' in data &&
          data.blockchain_account_id != undefined
        ) {
          this.blockchain_account_id = data.blockchain_account_id;
        }
      }
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get type() {
      return pb_1.Message.getFieldWithDefault(this, 2, '') as string;
    }
    set type(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get controller() {
      return pb_1.Message.getFieldWithDefault(this, 3, '') as string;
    }
    set controller(value: string) {
      pb_1.Message.setField(this, 3, value);
    }
    get public_key_multibase() {
      return pb_1.Message.getFieldWithDefault(this, 4, '') as string;
    }
    set public_key_multibase(value: string) {
      pb_1.Message.setOneofField(this, 4, this.#one_of_decls[0], value);
    }
    get has_public_key_multibase() {
      return pb_1.Message.getField(this, 4) != null;
    }
    get blockchain_account_id() {
      return pb_1.Message.getFieldWithDefault(this, 5, '') as string;
    }
    set blockchain_account_id(value: string) {
      pb_1.Message.setOneofField(this, 5, this.#one_of_decls[1], value);
    }
    get has_blockchain_account_id() {
      return pb_1.Message.getField(this, 5) != null;
    }
    get _public_key_multibase() {
      const cases: {
        [index: number]: 'none' | 'public_key_multibase';
      } = {
        0: 'none',
        4: 'public_key_multibase'
      };
      return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    get _blockchain_account_id() {
      const cases: {
        [index: number]: 'none' | 'blockchain_account_id';
      } = {
        0: 'none',
        5: 'blockchain_account_id'
      };
      return cases[pb_1.Message.computeOneofCase(this, [5])];
    }
    static fromObject(data: {
      id?: string;
      type?: string;
      controller?: string;
      public_key_multibase?: string;
      blockchain_account_id?: string;
    }): VerificationMethod {
      const message = new VerificationMethod({});
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.type != null) {
        message.type = data.type;
      }
      if (data.controller != null) {
        message.controller = data.controller;
      }
      if (data.public_key_multibase != null) {
        message.public_key_multibase = data.public_key_multibase;
      }
      if (data.blockchain_account_id != null) {
        message.blockchain_account_id = data.blockchain_account_id;
      }
      return message;
    }
    toObject() {
      const data: {
        id?: string;
        type?: string;
        controller?: string;
        public_key_multibase?: string;
        blockchain_account_id?: string;
      } = {};
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.type != null) {
        data.type = this.type;
      }
      if (this.controller != null) {
        data.controller = this.controller;
      }
      if (this.public_key_multibase != null) {
        data.public_key_multibase = this.public_key_multibase;
      }
      if (this.blockchain_account_id != null) {
        data.blockchain_account_id = this.blockchain_account_id;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id.length) writer.writeString(1, this.id);
      if (this.type.length) writer.writeString(2, this.type);
      if (this.controller.length) writer.writeString(3, this.controller);
      if (this.has_public_key_multibase)
        writer.writeString(4, this.public_key_multibase);
      if (this.has_blockchain_account_id)
        writer.writeString(5, this.blockchain_account_id);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(
      bytes: Uint8Array | pb_1.BinaryReader
    ): VerificationMethod {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new VerificationMethod();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.id = reader.readString();
            break;
          case 2:
            message.type = reader.readString();
            break;
          case 3:
            message.controller = reader.readString();
            break;
          case 4:
            message.public_key_multibase = reader.readString();
            break;
          case 5:
            message.blockchain_account_id = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): VerificationMethod {
      return VerificationMethod.deserialize(bytes);
    }
  }
  export class Signature extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            type?: string;
            issuer?: string;
            hash?: string;
          }
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('type' in data && data.type != undefined) {
          this.type = data.type;
        }
        if ('issuer' in data && data.issuer != undefined) {
          this.issuer = data.issuer;
        }
        if ('hash' in data && data.hash != undefined) {
          this.hash = data.hash;
        }
      }
    }
    get type() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set type(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get issuer() {
      return pb_1.Message.getFieldWithDefault(this, 2, '') as string;
    }
    set issuer(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get hash() {
      return pb_1.Message.getFieldWithDefault(this, 3, '') as string;
    }
    set hash(value: string) {
      pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
      type?: string;
      issuer?: string;
      hash?: string;
    }): Signature {
      const message = new Signature({});
      if (data.type != null) {
        message.type = data.type;
      }
      if (data.issuer != null) {
        message.issuer = data.issuer;
      }
      if (data.hash != null) {
        message.hash = data.hash;
      }
      return message;
    }
    toObject() {
      const data: {
        type?: string;
        issuer?: string;
        hash?: string;
      } = {};
      if (this.type != null) {
        data.type = this.type;
      }
      if (this.issuer != null) {
        data.issuer = this.issuer;
      }
      if (this.hash != null) {
        data.hash = this.hash;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.type.length) writer.writeString(1, this.type);
      if (this.issuer.length) writer.writeString(2, this.issuer);
      if (this.hash.length) writer.writeString(3, this.hash);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Signature {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new Signature();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.type = reader.readString();
            break;
          case 2:
            message.issuer = reader.readString();
            break;
          case 3:
            message.hash = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Signature {
      return Signature.deserialize(bytes);
    }
  }
  export class Service extends pb_1.Message {
    #one_of_decls: number[][] = [[3], [4]];
    constructor(
      data?:
        | any[]
        | ({
            id?: string;
            type?: string;
          } & (
            | {
                service_endpoint?: string;
              }
            | {
                data?: string;
              }
          ))
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('id' in data && data.id != undefined) {
          this.id = data.id;
        }
        if ('type' in data && data.type != undefined) {
          this.type = data.type;
        }
        if ('service_endpoint' in data && data.service_endpoint != undefined) {
          this.service_endpoint = data.service_endpoint;
        }
        if ('data' in data && data.data != undefined) {
          this.data = data.data;
        }
      }
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get type() {
      return pb_1.Message.getFieldWithDefault(this, 2, '') as string;
    }
    set type(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get service_endpoint() {
      return pb_1.Message.getFieldWithDefault(this, 3, '') as string;
    }
    set service_endpoint(value: string) {
      pb_1.Message.setOneofField(this, 3, this.#one_of_decls[0], value);
    }
    get has_service_endpoint() {
      return pb_1.Message.getField(this, 3) != null;
    }
    get data() {
      return pb_1.Message.getFieldWithDefault(this, 4, '') as string;
    }
    set data(value: string) {
      pb_1.Message.setOneofField(this, 4, this.#one_of_decls[1], value);
    }
    get has_data() {
      return pb_1.Message.getField(this, 4) != null;
    }
    get _service_endpoint() {
      const cases: {
        [index: number]: 'none' | 'service_endpoint';
      } = {
        0: 'none',
        3: 'service_endpoint'
      };
      return cases[pb_1.Message.computeOneofCase(this, [3])];
    }
    get _data() {
      const cases: {
        [index: number]: 'none' | 'data';
      } = {
        0: 'none',
        4: 'data'
      };
      return cases[pb_1.Message.computeOneofCase(this, [4])];
    }
    static fromObject(data: {
      id?: string;
      type?: string;
      service_endpoint?: string;
      data?: string;
    }): Service {
      const message = new Service({});
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.type != null) {
        message.type = data.type;
      }
      if (data.service_endpoint != null) {
        message.service_endpoint = data.service_endpoint;
      }
      if (data.data != null) {
        message.data = data.data;
      }
      return message;
    }
    toObject() {
      const data: {
        id?: string;
        type?: string;
        service_endpoint?: string;
        data?: string;
      } = {};
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.type != null) {
        data.type = this.type;
      }
      if (this.service_endpoint != null) {
        data.service_endpoint = this.service_endpoint;
      }
      if (this.data != null) {
        data.data = this.data;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id.length) writer.writeString(1, this.id);
      if (this.type.length) writer.writeString(2, this.type);
      if (this.has_service_endpoint)
        writer.writeString(3, this.service_endpoint);
      if (this.has_data) writer.writeString(4, this.data);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Service {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new Service();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.id = reader.readString();
            break;
          case 2:
            message.type = reader.readString();
            break;
          case 3:
            message.service_endpoint = reader.readString();
            break;
          case 4:
            message.data = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Service {
      return Service.deserialize(bytes);
    }
  }
  export class Document extends pb_1.Message {
    #one_of_decls: number[][] = [[7]];
    constructor(
      data?:
        | any[]
        | ({
            id?: string;
            controller?: string;
            verification_methods?: VerificationMethod[];
            signature?: Signature;
            services?: Service[];
            authentications?: string[];
          } & {
            verifiable_credential?: VerifiableCredential;
          })
    ) {
      super();
      pb_1.Message.initialize(
        this,
        Array.isArray(data) ? data : [],
        0,
        -1,
        [3, 5, 6],
        this.#one_of_decls
      );
      if (!Array.isArray(data) && typeof data == 'object') {
        if ('id' in data && data.id != undefined) {
          this.id = data.id;
        }
        if ('controller' in data && data.controller != undefined) {
          this.controller = data.controller;
        }
        if (
          'verification_methods' in data &&
          data.verification_methods != undefined
        ) {
          this.verification_methods = data.verification_methods;
        }
        if ('signature' in data && data.signature != undefined) {
          this.signature = data.signature;
        }
        if ('services' in data && data.services != undefined) {
          this.services = data.services;
        }
        if ('authentications' in data && data.authentications != undefined) {
          this.authentications = data.authentications;
        }
        if (
          'verifiable_credential' in data &&
          data.verifiable_credential != undefined
        ) {
          this.verifiable_credential = data.verifiable_credential;
        }
      }
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 1, '') as string;
    }
    set id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get controller() {
      return pb_1.Message.getFieldWithDefault(this, 2, '') as string;
    }
    set controller(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get verification_methods() {
      return pb_1.Message.getRepeatedWrapperField(
        this,
        VerificationMethod,
        3
      ) as VerificationMethod[];
    }
    set verification_methods(value: VerificationMethod[]) {
      pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    get signature() {
      return pb_1.Message.getWrapperField(this, Signature, 4) as Signature;
    }
    set signature(value: Signature) {
      pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_signature() {
      return pb_1.Message.getField(this, 4) != null;
    }
    get services() {
      return pb_1.Message.getRepeatedWrapperField(
        this,
        Service,
        5
      ) as Service[];
    }
    set services(value: Service[]) {
      pb_1.Message.setRepeatedWrapperField(this, 5, value);
    }
    get authentications() {
      return pb_1.Message.getFieldWithDefault(this, 6, []) as string[];
    }
    set authentications(value: string[]) {
      pb_1.Message.setField(this, 6, value);
    }
    get verifiable_credential() {
      return pb_1.Message.getWrapperField(
        this,
        VerifiableCredential,
        7
      ) as VerifiableCredential;
    }
    set verifiable_credential(value: VerifiableCredential) {
      pb_1.Message.setOneofWrapperField(this, 7, this.#one_of_decls[0], value);
    }
    get has_verifiable_credential() {
      return pb_1.Message.getField(this, 7) != null;
    }
    get _verifiable_credential() {
      const cases: {
        [index: number]: 'none' | 'verifiable_credential';
      } = {
        0: 'none',
        7: 'verifiable_credential'
      };
      return cases[pb_1.Message.computeOneofCase(this, [7])];
    }
    static fromObject(data: {
      id?: string;
      controller?: string;
      verification_methods?: ReturnType<
        typeof VerificationMethod.prototype.toObject
      >[];
      signature?: ReturnType<typeof Signature.prototype.toObject>;
      services?: ReturnType<typeof Service.prototype.toObject>[];
      authentications?: string[];
      verifiable_credential?: ReturnType<
        typeof VerifiableCredential.prototype.toObject
      >;
    }): Document {
      const message = new Document({});
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.controller != null) {
        message.controller = data.controller;
      }
      if (data.verification_methods != null) {
        message.verification_methods = data.verification_methods.map((item) =>
          VerificationMethod.fromObject(item)
        );
      }
      if (data.signature != null) {
        message.signature = Signature.fromObject(data.signature);
      }
      if (data.services != null) {
        message.services = data.services.map((item) =>
          Service.fromObject(item)
        );
      }
      if (data.authentications != null) {
        message.authentications = data.authentications;
      }
      if (data.verifiable_credential != null) {
        message.verifiable_credential = VerifiableCredential.fromObject(
          data.verifiable_credential
        );
      }
      return message;
    }
    toObject() {
      const data: {
        id?: string;
        controller?: string;
        verification_methods?: ReturnType<
          typeof VerificationMethod.prototype.toObject
        >[];
        signature?: ReturnType<typeof Signature.prototype.toObject>;
        services?: ReturnType<typeof Service.prototype.toObject>[];
        authentications?: string[];
        verifiable_credential?: ReturnType<
          typeof VerifiableCredential.prototype.toObject
        >;
      } = {};
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.controller != null) {
        data.controller = this.controller;
      }
      if (this.verification_methods != null) {
        data.verification_methods = this.verification_methods.map(
          (item: VerificationMethod) => item.toObject()
        );
      }
      if (this.signature != null) {
        data.signature = this.signature.toObject();
      }
      if (this.services != null) {
        data.services = this.services.map((item: Service) => item.toObject());
      }
      if (this.authentications != null) {
        data.authentications = this.authentications;
      }
      if (this.verifiable_credential != null) {
        data.verifiable_credential = this.verifiable_credential.toObject();
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id.length) writer.writeString(1, this.id);
      if (this.controller.length) writer.writeString(2, this.controller);
      if (this.verification_methods.length)
        writer.writeRepeatedMessage(
          3,
          this.verification_methods,
          (item: VerificationMethod) => item.serialize(writer)
        );
      if (this.has_signature)
        writer.writeMessage(4, this.signature, () =>
          this.signature.serialize(writer)
        );
      if (this.services.length)
        writer.writeRepeatedMessage(5, this.services, (item: Service) =>
          item.serialize(writer)
        );
      if (this.authentications.length)
        writer.writeRepeatedString(6, this.authentications);
      if (this.has_verifiable_credential)
        writer.writeMessage(7, this.verifiable_credential, () =>
          this.verifiable_credential.serialize(writer)
        );
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Document {
      const reader =
          bytes instanceof pb_1.BinaryReader
            ? bytes
            : new pb_1.BinaryReader(bytes),
        message = new Document();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.id = reader.readString();
            break;
          case 2:
            message.controller = reader.readString();
            break;
          case 3:
            reader.readMessage(message.verification_methods, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                3,
                VerificationMethod.deserialize(reader),
                VerificationMethod
              )
            );
            break;
          case 4:
            reader.readMessage(
              message.signature,
              () => (message.signature = Signature.deserialize(reader))
            );
            break;
          case 5:
            reader.readMessage(message.services, () =>
              pb_1.Message.addToRepeatedWrapperField(
                message,
                5,
                Service.deserialize(reader),
                Service
              )
            );
            break;
          case 6:
            pb_1.Message.addToRepeatedField(message, 6, reader.readString());
            break;
          case 7:
            reader.readMessage(
              message.verifiable_credential,
              () =>
                (message.verifiable_credential =
                  VerifiableCredential.deserialize(reader))
            );
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Document {
      return Document.deserialize(bytes);
    }
  }
}
